vim.keymap.set('n','<C-A>',':Addtc<CR>')
vim.keymap.set('n','<C-T>',':Test<CR>')
vim.keymap.set('n','<C-s>',':Submit<CR>')
vim.keymap.set('n','tt',':ToggleTerm direction=float<CR>')
vim.keymap.set('n','tT',':ToggleTerm direction=vertical size=40<CR>')
vim.keymap.set('n','LL',':Lazy<CR>')
vim.keymap.set('n','ff',':Neotree<CR>')
vim.keymap.set('n','qQ','<C-w><C-w>:q<CR>')
vim.keymap.set('n','qq',':q<CR>')
vim.keymap.set('n','Ll',':LspInstallInfo<CR>')
vim.keymap.set('n','gG',':TermExec cmd="lazygit" direction=float<CR>')
