vim.keymap.set('n','<C-A>',':Addtc<CR>')
vim.keymap.set('n','<C-T>',':Test<CR>')
vim.keymap.set('n','<C-s>',':submit<CR>')
vim.keymap.set('n','tt',':ToggleTerm direction=float<CR>')
vim.keymap.set('n','tT',':ToggleTerm direction=horizontal<CR>')
vim.keymap.set('n','ll',':Lazy<CR>')
vim.keymap.set('n','ff',':Neotree<CR>')
vim.keymap.set('n','qQ','<C-w><C-w>:q<CR>')
vim.keymap.set('n','qq',':q<CR>')
vim.keymap.set('n','lL',':LspInstallInfo<CR>')
